Feture/post product
ZeshanShahid79/kitchen-storage pull request #4
Opened 2023-07-12 10:15 UTC by ZeshanShahid79

2023-07-12 15:06 UTC, MoinMarcell requested changes
some suggestions down belo :) nice job so far!

2023-07-12 15:06 UTC, lostspezi commented on backend/src/main/java/com/example/backend/products/ProductController.java
> +    @ResponseStatus(HttpStatus.CREATED)
Nice!

2023-07-12 15:06 UTC, MoinMarcell commented on backend/src/main/java/com/example/backend/products/ProductService.java
> +        Product productToSave = new Product(id, productWithouthId.productName());
Man könnte überlegen eine Methode zu schreiben, die ein  Product mit Id zurückgibt :-)

2023-07-12 15:06 UTC, lostspezi commented on backend/src/main/java/com/example/backend/products/UuidService.java
> +@NoArgsConstructor
wozu?

2023-07-12 15:06 UTC, lostspezi commented on backend/src/test/java/com/example/backend/Product/ProductIntegrationTest.java
> +                        {"productName": "apple"}
Überlegen den ObjectMapper zu nutzen

2023-07-12 15:06 UTC, lostspezi commented on frontend/src/App.tsx
> +            <Stack alignItems={"center"}>
Warum ein Stack? Es gibt Box und Container :-)

2023-07-12 15:06 UTC, lostspezi commented on frontend/src/components/productAddForm.tsx
> +                setProductName(responseData.productName);
Wieso setzt du die Response in den State?

2023-07-12 15:06 UTC, lostspezi commented on frontend/src/components/productAddForm.tsx
> +            }).finally(() => setProductName(""))
Wenn du an der stelle den state eh wieder auf einen Leerstring setzt?

2023-07-12 15:06 UTC, lostspezi commented on frontend/src/hooks/useProducts.tsx
> +    }, [products]);
Endlosschleifen potential

2023-07-23 15:32 UTC, Dskottke approved these changes
Ich habe dir noch ein paar Sachen aufgeschrieben. 😀 Ist aber nichts von riesen Bedeutung. Sieht gut aus !

2023-07-23 15:32 UTC, Dskottke commented on backend/src/test/java/com/example/backend/Product/ProductServiceTest.java
> +        ProductWithouthId testProductWothouthId = new ProductWithouthId("apple");
Kleiner Schreibfehler .. testProductW"o"thoutId

2023-07-23 15:32 UTC, Dskottke commented on frontend/src/App.tsx
> +    const {products, fetchProductsAfterAdd} = useProducts()
Man könnte sich überlegen es einfach nur fetchProducts zu nennen und nicht zu detailliert zu sein... Da du es später an anderen Stellen wieder nutzen könntest. Kannst du aber auch dann ändern.

2023-10-09 08:04 UTC, merged

2023-10-09 08:42 UTC, Dskottke approved these changes